import "./globals.css";
import localFont from "next/font/local";

const IRANSansX = localFont({
  src: [
    {
      path: "../public/fonts/woff2/IRANSansX-Black.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-DemiBold.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-ExtraBlack.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-ExtraBold.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Heavy.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-UltraLight.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/woff2/IRANSansX-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={IRANSansX.className}>{children}</body>
    </html>
  );
}
